[package]
name = "payphone-token"
version = "0.2.0"
edition = "2024"

[dependencies]
payphone-auth = {
    path = "../payphone-auth"
}

ed25519-dalek = {
    version = "3",
    features = [
        "rand_core",
        "pkcs8"
    ]
}

rand_core = {
    version = "0.9",
    features = [
        "os_rng"
    ]
}

x25519-dalek = { version = "2", features = ["static_secrets"] }