[package]
name = "payphone-transport"
version = "0.1.0"
edition = "2024"

[dependencies]
payphone-core = { path = "../payphone-core" }

quinn = { version = "0.11.11", features = [
    "runtime-tokio",
    "rustls-ring"
] }

rustls = "0.23"
rcgen = "0.14"
bytes = "1"
sha2 = "0.11"

rand_core = {
    version = "0.9",
    features = [
        "os_rng"
    ]
}

tokio = { version = "1", features = [
    "rt-multi-thread",
    "macros",
    "net",
    "time",
    "sync"
] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"